# Assignment - 1: Pandas Basics
Dataset: `Combined_dataset.csv`

In [1]:
import pandas as pd
import numpy as np

### Step 1: Load a CSV dataset into a Pandas DataFrame

In [2]:
df = pd.read_csv('Combined_dataset.csv')
# print(df)

### Step 2: Explore Data

In [3]:
# Shape
print('Shape')
print(df.shape)

# Colums as list
print('\nColumns')
print(df.columns.tolist())

# Data types
print('\nData Types')
print(df.dtypes)

# Head gives first 5 rows and tail gives last 5 rows of the dataframe
print('\nHead')
display(df.head())
print('\nTail')
display(df.tail())

Shape
(1000, 24)

Columns
['product_id', 'title', 'product_description', 'rating', 'ratings_count', 'initial_price', 'discount', 'final_price', 'currency', 'images', 'delivery_options', 'product_details', 'breadcrumbs', 'product_specifications', 'amount_of_stars', 'what_customers_said', 'seller_name', 'sizes', 'videos', 'seller_information', 'variations', 'best_offer', 'more_offers', 'category']

Data Types
product_id                  int64
title                         str
product_description           str
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                   str
currency                      str
images                        str
delivery_options              str
product_details               str
breadcrumbs                   str
product_specifications        str
amount_of_stars               str
what_customers_said           str
seller_name                   str
sizes                         str
videos                        str
seller_information            str
variations                    str
best_offer                    str
more_offers                   str
category                      str
dtype: object

Head

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

Tail

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

### Step 3: Handle Missing Values

In [4]:
print("Missing values before:\n")
print(df.isnull().sum()[df.isnull().sum() > 0])

# DROP colums that have more than 50% missing values
half_count = len(df) * 0.5 
df = df.dropna(axis=1, thresh=half_count)

# 2. FILL missing data in columns with appropriate values 
numeric_cols = df.select_dtypes(include=['number']).columns
text_cols = df.select_dtypes(include=['object','str']).columns

for col in text_cols:
    if df[col].isnull().sum() > 0:
        df[col] = df[col].fillna('Not Available')

for col in numeric_cols:
    if df[col].isnull().sum() > 0:
        df[col] = df[col].fillna(0)

# 4. VERIFY the data
print("\nMissing Values AFTER Cleaning:",df.isnull().sum().sum())

Missing values before:

discount               121
what_customers_said    573
seller_name            301
videos                 781
seller_information     301
variations             562
dtype: int64

Missing Values AFTER Cleaning: 0

### Step 4: Perform Basic Operations

In [5]:
# Filter rows to get products with an initial price greater than 1000
premium_products = df[df['initial_price'] > 1000]

# Select columns to view only title, category, and price
selected_cols = premium_products[['title', 'category', 'initial_price']]

display(selected_cols)

                 title   category  initial_price
0          Lino Perros  backpacks           3995
1       Tommy Hilfiger  backpacks           2899
2                Lavie  backpacks           2999
3               F Gear  backpacks           1675
4            MYTRIDENT  bath-robe           2899
..                 ...        ...            ...
994  French Connection    watches           6250
995              KREDO    watches          11890
996              GUESS    watches           8900
997           GIORDANO    watches           7950
998           Fastrack    watches           3295

[832 rows x 3 columns]

### Step 5: Remove Duplicates

In [6]:
initial_len = len(df)
# print(initial_len)
df = df.drop_duplicates()
print(f"Dropped {initial_len - len(df)} rows.")

Dropped 0 rows.

### Step 6: Create a Derived Column (total_amount = price * quantity)
*Note: Since the provided Kaggle dataset lacked a 'quantity' column, I generated a mock column to successfully demonstrate Step 6*

In [7]:
# 1. Create a dummy quantity column (random numbers between 1 and 5)
np.random.seed(42)
df['quantity'] = np.random.randint(1, 6, size=len(df))

# 2. Create the derived column
df['total_amount'] = df['initial_price'] * df['quantity']

display(df[['title', 'initial_price', 'quantity', 'total_amount']])

              title  initial_price  quantity  total_amount
0       Lino Perros           3995         4         15980
1    Tommy Hilfiger           2899         5         14495
2             Lavie           2999         3          8997
3            F Gear           1675         5          8375
4         MYTRIDENT           2899         5         14495
..              ...            ...       ...           ...
995           KREDO          11890         2         23780
996           GUESS           8900         1          8900
997        GIORDANO           7950         1          7950
998        Fastrack           3295         4         13180
999         BOLDFIT            699         3          2097

[1000 rows x 4 columns]

### Step 7: Save the Cleaned Dataset

In [8]:
df.to_csv('Cleaned_Combined_dataset.csv', index=False)
print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!